/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package teeth.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TreatmentHistory service. Represents a row in the &quot;treatment_history&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>teeth.model.impl.TreatmentHistoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>teeth.model.impl.TreatmentHistoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreatmentHistory
 * @generated
 */
@ProviderType
public interface TreatmentHistoryModel
	extends BaseModel<TreatmentHistory>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a treatment history model instance should use the {@link TreatmentHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this treatment history.
	 *
	 * @return the primary key of this treatment history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this treatment history.
	 *
	 * @param primaryKey the primary key of this treatment history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this treatment history.
	 *
	 * @return the uuid of this treatment history
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this treatment history.
	 *
	 * @param uuid the uuid of this treatment history
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the treatment ID of this treatment history.
	 *
	 * @return the treatment ID of this treatment history
	 */
	public long getTreatmentID();

	/**
	 * Sets the treatment ID of this treatment history.
	 *
	 * @param treatmentID the treatment ID of this treatment history
	 */
	public void setTreatmentID(long treatmentID);

	/**
	 * Returns the crf ID of this treatment history.
	 *
	 * @return the crf ID of this treatment history
	 */
	public long getCrfId();

	/**
	 * Sets the crf ID of this treatment history.
	 *
	 * @param crfId the crf ID of this treatment history
	 */
	public void setCrfId(long crfId);

	/**
	 * Returns the link ID of this treatment history.
	 *
	 * @return the link ID of this treatment history
	 */
	public long getLinkId();

	/**
	 * Sets the link ID of this treatment history.
	 *
	 * @param linkId the link ID of this treatment history
	 */
	public void setLinkId(long linkId);

	/**
	 * Returns the patient ID of this treatment history.
	 *
	 * @return the patient ID of this treatment history
	 */
	public long getPatientID();

	/**
	 * Sets the patient ID of this treatment history.
	 *
	 * @param patientID the patient ID of this treatment history
	 */
	public void setPatientID(long patientID);

	/**
	 * Returns the edited user ID of this treatment history.
	 *
	 * @return the edited user ID of this treatment history
	 */
	public long getEditedUserID();

	/**
	 * Sets the edited user ID of this treatment history.
	 *
	 * @param editedUserID the edited user ID of this treatment history
	 */
	public void setEditedUserID(long editedUserID);

	/**
	 * Returns the teeth num of this treatment history.
	 *
	 * @return the teeth num of this treatment history
	 */
	public long getTeethNum();

	/**
	 * Sets the teeth num of this treatment history.
	 *
	 * @param teethNum the teeth num of this treatment history
	 */
	public void setTeethNum(long teethNum);

	/**
	 * Returns the treatment date of this treatment history.
	 *
	 * @return the treatment date of this treatment history
	 */
	public Date getTreatmentDate();

	/**
	 * Sets the treatment date of this treatment history.
	 *
	 * @param treatmentDate the treatment date of this treatment history
	 */
	public void setTreatmentDate(Date treatmentDate);

	/**
	 * Returns the edited date of this treatment history.
	 *
	 * @return the edited date of this treatment history
	 */
	public Date getEditedDate();

	/**
	 * Sets the edited date of this treatment history.
	 *
	 * @param editedDate the edited date of this treatment history
	 */
	public void setEditedDate(Date editedDate);

	/**
	 * Returns the treatment of this treatment history.
	 *
	 * @return the treatment of this treatment history
	 */
	@AutoEscape
	public String getTreatment();

	/**
	 * Sets the treatment of this treatment history.
	 *
	 * @param treatment the treatment of this treatment history
	 */
	public void setTreatment(String treatment);

	/**
	 * Returns the state of this treatment history.
	 *
	 * @return the state of this treatment history
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this treatment history.
	 *
	 * @param state the state of this treatment history
	 */
	public void setState(String state);

	/**
	 * Returns the group ID of this treatment history.
	 *
	 * @return the group ID of this treatment history
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this treatment history.
	 *
	 * @param groupId the group ID of this treatment history
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this treatment history.
	 *
	 * @return the company ID of this treatment history
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this treatment history.
	 *
	 * @param companyId the company ID of this treatment history
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this treatment history.
	 *
	 * @return the user ID of this treatment history
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this treatment history.
	 *
	 * @param userId the user ID of this treatment history
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this treatment history.
	 *
	 * @return the user uuid of this treatment history
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this treatment history.
	 *
	 * @param userUuid the user uuid of this treatment history
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this treatment history.
	 *
	 * @return the user name of this treatment history
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this treatment history.
	 *
	 * @param userName the user name of this treatment history
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this treatment history.
	 *
	 * @return the create date of this treatment history
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this treatment history.
	 *
	 * @param createDate the create date of this treatment history
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this treatment history.
	 *
	 * @return the modified date of this treatment history
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this treatment history.
	 *
	 * @param modifiedDate the modified date of this treatment history
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this treatment history.
	 *
	 * @return the status of this treatment history
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this treatment history.
	 *
	 * @param status the status of this treatment history
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this treatment history.
	 *
	 * @return the status by user ID of this treatment history
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this treatment history.
	 *
	 * @param statusByUserId the status by user ID of this treatment history
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this treatment history.
	 *
	 * @return the status by user uuid of this treatment history
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this treatment history.
	 *
	 * @param statusByUserUuid the status by user uuid of this treatment history
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this treatment history.
	 *
	 * @return the status by user name of this treatment history
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this treatment history.
	 *
	 * @param statusByUserName the status by user name of this treatment history
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this treatment history.
	 *
	 * @return the status date of this treatment history
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this treatment history.
	 *
	 * @param statusDate the status date of this treatment history
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this treatment history is approved.
	 *
	 * @return <code>true</code> if this treatment history is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this treatment history is denied.
	 *
	 * @return <code>true</code> if this treatment history is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this treatment history is a draft.
	 *
	 * @return <code>true</code> if this treatment history is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this treatment history is expired.
	 *
	 * @return <code>true</code> if this treatment history is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this treatment history is inactive.
	 *
	 * @return <code>true</code> if this treatment history is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this treatment history is incomplete.
	 *
	 * @return <code>true</code> if this treatment history is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this treatment history is pending.
	 *
	 * @return <code>true</code> if this treatment history is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this treatment history is scheduled.
	 *
	 * @return <code>true</code> if this treatment history is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}