/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package teeth.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TreatmentHistory service. Represents a row in the &quot;treatment_history&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>teeth.model.impl.TreatmentHistoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>teeth.model.impl.TreatmentHistoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreatmentHistory
 * @generated
 */
@ProviderType
public interface TreatmentHistoryModel extends BaseModel<TreatmentHistory> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a treatment history model instance should use the {@link TreatmentHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this treatment history.
	 *
	 * @return the primary key of this treatment history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this treatment history.
	 *
	 * @param primaryKey the primary key of this treatment history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the treatment ID of this treatment history.
	 *
	 * @return the treatment ID of this treatment history
	 */
	public long getTreatmentID();

	/**
	 * Sets the treatment ID of this treatment history.
	 *
	 * @param treatmentID the treatment ID of this treatment history
	 */
	public void setTreatmentID(long treatmentID);

	/**
	 * Returns the patient ID of this treatment history.
	 *
	 * @return the patient ID of this treatment history
	 */
	public long getPatientID();

	/**
	 * Sets the patient ID of this treatment history.
	 *
	 * @param patientID the patient ID of this treatment history
	 */
	public void setPatientID(long patientID);

	/**
	 * Returns the edited user ID of this treatment history.
	 *
	 * @return the edited user ID of this treatment history
	 */
	public long getEditedUserID();

	/**
	 * Sets the edited user ID of this treatment history.
	 *
	 * @param editedUserID the edited user ID of this treatment history
	 */
	public void setEditedUserID(long editedUserID);

	/**
	 * Returns the teeth num of this treatment history.
	 *
	 * @return the teeth num of this treatment history
	 */
	public long getTeethNum();

	/**
	 * Sets the teeth num of this treatment history.
	 *
	 * @param teethNum the teeth num of this treatment history
	 */
	public void setTeethNum(long teethNum);

	/**
	 * Returns the treatment date of this treatment history.
	 *
	 * @return the treatment date of this treatment history
	 */
	public Date getTreatmentDate();

	/**
	 * Sets the treatment date of this treatment history.
	 *
	 * @param treatmentDate the treatment date of this treatment history
	 */
	public void setTreatmentDate(Date treatmentDate);

	/**
	 * Returns the edited date of this treatment history.
	 *
	 * @return the edited date of this treatment history
	 */
	public Date getEditedDate();

	/**
	 * Sets the edited date of this treatment history.
	 *
	 * @param editedDate the edited date of this treatment history
	 */
	public void setEditedDate(Date editedDate);

	/**
	 * Returns the treatment of this treatment history.
	 *
	 * @return the treatment of this treatment history
	 */
	@AutoEscape
	public String getTreatment();

	/**
	 * Sets the treatment of this treatment history.
	 *
	 * @param treatment the treatment of this treatment history
	 */
	public void setTreatment(String treatment);

	/**
	 * Returns the state of this treatment history.
	 *
	 * @return the state of this treatment history
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this treatment history.
	 *
	 * @param state the state of this treatment history
	 */
	public void setState(String state);

}