/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package teeth.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TreatmentAudit service. Represents a row in the &quot;treatment_audit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>teeth.model.impl.TreatmentAuditModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>teeth.model.impl.TreatmentAuditImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreatmentAudit
 * @generated
 */
@ProviderType
public interface TreatmentAuditModel extends BaseModel<TreatmentAudit> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a treatment audit model instance should use the {@link TreatmentAudit} interface instead.
	 */

	/**
	 * Returns the primary key of this treatment audit.
	 *
	 * @return the primary key of this treatment audit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this treatment audit.
	 *
	 * @param primaryKey the primary key of this treatment audit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit ID of this treatment audit.
	 *
	 * @return the audit ID of this treatment audit
	 */
	public long getAuditID();

	/**
	 * Sets the audit ID of this treatment audit.
	 *
	 * @param AuditID the audit ID of this treatment audit
	 */
	public void setAuditID(long AuditID);

	/**
	 * Returns the teeth num of this treatment audit.
	 *
	 * @return the teeth num of this treatment audit
	 */
	public long getTeethNum();

	/**
	 * Sets the teeth num of this treatment audit.
	 *
	 * @param teethNum the teeth num of this treatment audit
	 */
	public void setTeethNum(long teethNum);

	/**
	 * Returns the edited date of this treatment audit.
	 *
	 * @return the edited date of this treatment audit
	 */
	public Date getEditedDate();

	/**
	 * Sets the edited date of this treatment audit.
	 *
	 * @param editedDate the edited date of this treatment audit
	 */
	public void setEditedDate(Date editedDate);

	/**
	 * Returns the edited user ID of this treatment audit.
	 *
	 * @return the edited user ID of this treatment audit
	 */
	public long getEditedUserID();

	/**
	 * Sets the edited user ID of this treatment audit.
	 *
	 * @param editedUserID the edited user ID of this treatment audit
	 */
	public void setEditedUserID(long editedUserID);

	/**
	 * Returns the edit type of this treatment audit.
	 *
	 * @return the edit type of this treatment audit
	 */
	@AutoEscape
	public String getEditType();

	/**
	 * Sets the edit type of this treatment audit.
	 *
	 * @param editType the edit type of this treatment audit
	 */
	public void setEditType(String editType);

	/**
	 * Returns the treatment date of this treatment audit.
	 *
	 * @return the treatment date of this treatment audit
	 */
	public Date getTreatmentDate();

	/**
	 * Sets the treatment date of this treatment audit.
	 *
	 * @param treatmentDate the treatment date of this treatment audit
	 */
	public void setTreatmentDate(Date treatmentDate);

	/**
	 * Returns the before data of this treatment audit.
	 *
	 * @return the before data of this treatment audit
	 */
	@AutoEscape
	public String getBeforeData();

	/**
	 * Sets the before data of this treatment audit.
	 *
	 * @param beforeData the before data of this treatment audit
	 */
	public void setBeforeData(String beforeData);

	/**
	 * Returns the after data of this treatment audit.
	 *
	 * @return the after data of this treatment audit
	 */
	@AutoEscape
	public String getAfterData();

	/**
	 * Sets the after data of this treatment audit.
	 *
	 * @param afterData the after data of this treatment audit
	 */
	public void setAfterData(String afterData);

}