/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package teeth.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import teeth.model.TreatmentHistory;
import teeth.model.TreatmentHistoryModel;

/**
 * The base model implementation for the TreatmentHistory service. Represents a row in the &quot;treatment_history&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TreatmentHistoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TreatmentHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreatmentHistoryImpl
 * @generated
 */
public class TreatmentHistoryModelImpl
	extends BaseModelImpl<TreatmentHistory> implements TreatmentHistoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a treatment history model instance should use the <code>TreatmentHistory</code> interface instead.
	 */
	public static final String TABLE_NAME = "treatment_history";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"treatmentID", Types.BIGINT},
		{"patientID", Types.BIGINT}, {"editedUserID", Types.BIGINT},
		{"teethNum", Types.BIGINT}, {"treatmentDate", Types.TIMESTAMP},
		{"editedDate", Types.TIMESTAMP}, {"treatment", Types.VARCHAR},
		{"state_", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("treatmentID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("patientID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("editedUserID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("teethNum", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("treatmentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("editedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("treatment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("state_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table treatment_history (uuid_ VARCHAR(75) null,treatmentID LONG not null primary key,patientID LONG,editedUserID LONG,teethNum LONG,treatmentDate DATE null,editedDate DATE null,treatment VARCHAR(75) null,state_ VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table treatment_history";

	public static final String ORDER_BY_JPQL =
		" ORDER BY treatmentHistory.treatmentID ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY treatment_history.treatmentID ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long PATIENTID_COLUMN_BITMASK = 4L;

	public static final long STATUS_COLUMN_BITMASK = 8L;

	public static final long TEETHNUM_COLUMN_BITMASK = 16L;

	public static final long TREATMENT_COLUMN_BITMASK = 32L;

	public static final long TREATMENTDATE_COLUMN_BITMASK = 64L;

	public static final long UUID_COLUMN_BITMASK = 128L;

	public static final long TREATMENTID_COLUMN_BITMASK = 256L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public TreatmentHistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _treatmentID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTreatmentID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _treatmentID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TreatmentHistory.class;
	}

	@Override
	public String getModelClassName() {
		return TreatmentHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TreatmentHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TreatmentHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreatmentHistory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TreatmentHistory)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TreatmentHistory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TreatmentHistory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TreatmentHistory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TreatmentHistory, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TreatmentHistory, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TreatmentHistory, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TreatmentHistory, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TreatmentHistory, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<TreatmentHistory, Object>>();
		Map<String, BiConsumer<TreatmentHistory, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TreatmentHistory, ?>>();

		attributeGetterFunctions.put("uuid", TreatmentHistory::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<TreatmentHistory, String>)TreatmentHistory::setUuid);
		attributeGetterFunctions.put(
			"treatmentID", TreatmentHistory::getTreatmentID);
		attributeSetterBiConsumers.put(
			"treatmentID",
			(BiConsumer<TreatmentHistory, Long>)
				TreatmentHistory::setTreatmentID);
		attributeGetterFunctions.put(
			"patientID", TreatmentHistory::getPatientID);
		attributeSetterBiConsumers.put(
			"patientID",
			(BiConsumer<TreatmentHistory, Long>)TreatmentHistory::setPatientID);
		attributeGetterFunctions.put(
			"editedUserID", TreatmentHistory::getEditedUserID);
		attributeSetterBiConsumers.put(
			"editedUserID",
			(BiConsumer<TreatmentHistory, Long>)
				TreatmentHistory::setEditedUserID);
		attributeGetterFunctions.put("teethNum", TreatmentHistory::getTeethNum);
		attributeSetterBiConsumers.put(
			"teethNum",
			(BiConsumer<TreatmentHistory, Long>)TreatmentHistory::setTeethNum);
		attributeGetterFunctions.put(
			"treatmentDate", TreatmentHistory::getTreatmentDate);
		attributeSetterBiConsumers.put(
			"treatmentDate",
			(BiConsumer<TreatmentHistory, Date>)
				TreatmentHistory::setTreatmentDate);
		attributeGetterFunctions.put(
			"editedDate", TreatmentHistory::getEditedDate);
		attributeSetterBiConsumers.put(
			"editedDate",
			(BiConsumer<TreatmentHistory, Date>)
				TreatmentHistory::setEditedDate);
		attributeGetterFunctions.put(
			"treatment", TreatmentHistory::getTreatment);
		attributeSetterBiConsumers.put(
			"treatment",
			(BiConsumer<TreatmentHistory, String>)
				TreatmentHistory::setTreatment);
		attributeGetterFunctions.put("state", TreatmentHistory::getState);
		attributeSetterBiConsumers.put(
			"state",
			(BiConsumer<TreatmentHistory, String>)TreatmentHistory::setState);
		attributeGetterFunctions.put("groupId", TreatmentHistory::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TreatmentHistory, Long>)TreatmentHistory::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TreatmentHistory::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TreatmentHistory, Long>)TreatmentHistory::setCompanyId);
		attributeGetterFunctions.put("userId", TreatmentHistory::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<TreatmentHistory, Long>)TreatmentHistory::setUserId);
		attributeGetterFunctions.put("userName", TreatmentHistory::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TreatmentHistory, String>)
				TreatmentHistory::setUserName);
		attributeGetterFunctions.put(
			"createDate", TreatmentHistory::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TreatmentHistory, Date>)
				TreatmentHistory::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TreatmentHistory::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TreatmentHistory, Date>)
				TreatmentHistory::setModifiedDate);
		attributeGetterFunctions.put("status", TreatmentHistory::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<TreatmentHistory, Integer>)TreatmentHistory::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", TreatmentHistory::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<TreatmentHistory, Long>)
				TreatmentHistory::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", TreatmentHistory::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<TreatmentHistory, String>)
				TreatmentHistory::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", TreatmentHistory::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<TreatmentHistory, Date>)
				TreatmentHistory::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getTreatmentID() {
		return _treatmentID;
	}

	@Override
	public void setTreatmentID(long treatmentID) {
		_treatmentID = treatmentID;
	}

	@Override
	public long getPatientID() {
		return _patientID;
	}

	@Override
	public void setPatientID(long patientID) {
		_columnBitmask |= PATIENTID_COLUMN_BITMASK;

		if (!_setOriginalPatientID) {
			_setOriginalPatientID = true;

			_originalPatientID = _patientID;
		}

		_patientID = patientID;
	}

	public long getOriginalPatientID() {
		return _originalPatientID;
	}

	@Override
	public long getEditedUserID() {
		return _editedUserID;
	}

	@Override
	public void setEditedUserID(long editedUserID) {
		_editedUserID = editedUserID;
	}

	@Override
	public long getTeethNum() {
		return _teethNum;
	}

	@Override
	public void setTeethNum(long teethNum) {
		_columnBitmask |= TEETHNUM_COLUMN_BITMASK;

		if (!_setOriginalTeethNum) {
			_setOriginalTeethNum = true;

			_originalTeethNum = _teethNum;
		}

		_teethNum = teethNum;
	}

	public long getOriginalTeethNum() {
		return _originalTeethNum;
	}

	@Override
	public Date getTreatmentDate() {
		return _treatmentDate;
	}

	@Override
	public void setTreatmentDate(Date treatmentDate) {
		_columnBitmask |= TREATMENTDATE_COLUMN_BITMASK;

		if (_originalTreatmentDate == null) {
			_originalTreatmentDate = _treatmentDate;
		}

		_treatmentDate = treatmentDate;
	}

	public Date getOriginalTreatmentDate() {
		return _originalTreatmentDate;
	}

	@Override
	public Date getEditedDate() {
		return _editedDate;
	}

	@Override
	public void setEditedDate(Date editedDate) {
		_editedDate = editedDate;
	}

	@Override
	public String getTreatment() {
		if (_treatment == null) {
			return "";
		}
		else {
			return _treatment;
		}
	}

	@Override
	public void setTreatment(String treatment) {
		_columnBitmask |= TREATMENT_COLUMN_BITMASK;

		if (_originalTreatment == null) {
			_originalTreatment = _treatment;
		}

		_treatment = treatment;
	}

	public String getOriginalTreatment() {
		return GetterUtil.getString(_originalTreatment);
	}

	@Override
	public String getState() {
		if (_state == null) {
			return "";
		}
		else {
			return _state;
		}
	}

	@Override
	public void setState(String state) {
		_state = state;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TreatmentHistory.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TreatmentHistory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TreatmentHistory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TreatmentHistory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TreatmentHistoryImpl treatmentHistoryImpl = new TreatmentHistoryImpl();

		treatmentHistoryImpl.setUuid(getUuid());
		treatmentHistoryImpl.setTreatmentID(getTreatmentID());
		treatmentHistoryImpl.setPatientID(getPatientID());
		treatmentHistoryImpl.setEditedUserID(getEditedUserID());
		treatmentHistoryImpl.setTeethNum(getTeethNum());
		treatmentHistoryImpl.setTreatmentDate(getTreatmentDate());
		treatmentHistoryImpl.setEditedDate(getEditedDate());
		treatmentHistoryImpl.setTreatment(getTreatment());
		treatmentHistoryImpl.setState(getState());
		treatmentHistoryImpl.setGroupId(getGroupId());
		treatmentHistoryImpl.setCompanyId(getCompanyId());
		treatmentHistoryImpl.setUserId(getUserId());
		treatmentHistoryImpl.setUserName(getUserName());
		treatmentHistoryImpl.setCreateDate(getCreateDate());
		treatmentHistoryImpl.setModifiedDate(getModifiedDate());
		treatmentHistoryImpl.setStatus(getStatus());
		treatmentHistoryImpl.setStatusByUserId(getStatusByUserId());
		treatmentHistoryImpl.setStatusByUserName(getStatusByUserName());
		treatmentHistoryImpl.setStatusDate(getStatusDate());

		treatmentHistoryImpl.resetOriginalValues();

		return treatmentHistoryImpl;
	}

	@Override
	public int compareTo(TreatmentHistory treatmentHistory) {
		long primaryKey = treatmentHistory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TreatmentHistory)) {
			return false;
		}

		TreatmentHistory treatmentHistory = (TreatmentHistory)object;

		long primaryKey = treatmentHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalPatientID = _patientID;

		_setOriginalPatientID = false;

		_originalTeethNum = _teethNum;

		_setOriginalTeethNum = false;

		_originalTreatmentDate = _treatmentDate;

		_originalTreatment = _treatment;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_setModifiedDate = false;
		_originalStatus = _status;

		_setOriginalStatus = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TreatmentHistory> toCacheModel() {
		TreatmentHistoryCacheModel treatmentHistoryCacheModel =
			new TreatmentHistoryCacheModel();

		treatmentHistoryCacheModel.uuid = getUuid();

		String uuid = treatmentHistoryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			treatmentHistoryCacheModel.uuid = null;
		}

		treatmentHistoryCacheModel.treatmentID = getTreatmentID();

		treatmentHistoryCacheModel.patientID = getPatientID();

		treatmentHistoryCacheModel.editedUserID = getEditedUserID();

		treatmentHistoryCacheModel.teethNum = getTeethNum();

		Date treatmentDate = getTreatmentDate();

		if (treatmentDate != null) {
			treatmentHistoryCacheModel.treatmentDate = treatmentDate.getTime();
		}
		else {
			treatmentHistoryCacheModel.treatmentDate = Long.MIN_VALUE;
		}

		Date editedDate = getEditedDate();

		if (editedDate != null) {
			treatmentHistoryCacheModel.editedDate = editedDate.getTime();
		}
		else {
			treatmentHistoryCacheModel.editedDate = Long.MIN_VALUE;
		}

		treatmentHistoryCacheModel.treatment = getTreatment();

		String treatment = treatmentHistoryCacheModel.treatment;

		if ((treatment != null) && (treatment.length() == 0)) {
			treatmentHistoryCacheModel.treatment = null;
		}

		treatmentHistoryCacheModel.state = getState();

		String state = treatmentHistoryCacheModel.state;

		if ((state != null) && (state.length() == 0)) {
			treatmentHistoryCacheModel.state = null;
		}

		treatmentHistoryCacheModel.groupId = getGroupId();

		treatmentHistoryCacheModel.companyId = getCompanyId();

		treatmentHistoryCacheModel.userId = getUserId();

		treatmentHistoryCacheModel.userName = getUserName();

		String userName = treatmentHistoryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			treatmentHistoryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			treatmentHistoryCacheModel.createDate = createDate.getTime();
		}
		else {
			treatmentHistoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			treatmentHistoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			treatmentHistoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		treatmentHistoryCacheModel.status = getStatus();

		treatmentHistoryCacheModel.statusByUserId = getStatusByUserId();

		treatmentHistoryCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = treatmentHistoryCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			treatmentHistoryCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			treatmentHistoryCacheModel.statusDate = statusDate.getTime();
		}
		else {
			treatmentHistoryCacheModel.statusDate = Long.MIN_VALUE;
		}

		return treatmentHistoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TreatmentHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TreatmentHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreatmentHistory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TreatmentHistory)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TreatmentHistory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TreatmentHistory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreatmentHistory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TreatmentHistory)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TreatmentHistory>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TreatmentHistory.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _treatmentID;
	private long _patientID;
	private long _originalPatientID;
	private boolean _setOriginalPatientID;
	private long _editedUserID;
	private long _teethNum;
	private long _originalTeethNum;
	private boolean _setOriginalTeethNum;
	private Date _treatmentDate;
	private Date _originalTreatmentDate;
	private Date _editedDate;
	private String _treatment;
	private String _originalTreatment;
	private String _state;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private TreatmentHistory _escapedModel;

}