/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package teeth.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import teeth.model.TreatmentAudit;
import teeth.model.TreatmentAuditModel;

/**
 * The base model implementation for the TreatmentAudit service. Represents a row in the &quot;treatment_audit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TreatmentAuditModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TreatmentAuditImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreatmentAuditImpl
 * @generated
 */
public class TreatmentAuditModelImpl
	extends BaseModelImpl<TreatmentAudit> implements TreatmentAuditModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a treatment audit model instance should use the <code>TreatmentAudit</code> interface instead.
	 */
	public static final String TABLE_NAME = "treatment_audit";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"AuditID", Types.BIGINT},
		{"crfId", Types.BIGINT}, {"linkId", Types.BIGINT},
		{"patientID", Types.BIGINT}, {"teethNum", Types.BIGINT},
		{"editedDate", Types.TIMESTAMP}, {"editedUserID", Types.BIGINT},
		{"editType", Types.VARCHAR}, {"treatmentDate", Types.TIMESTAMP},
		{"beforeData", Types.VARCHAR}, {"afterData", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AuditID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("crfId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("linkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("patientID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("teethNum", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("editedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("editedUserID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("editType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("treatmentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("beforeData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("afterData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table treatment_audit (uuid_ VARCHAR(75) null,AuditID LONG not null primary key,crfId LONG,linkId LONG,patientID LONG,teethNum LONG,editedDate DATE null,editedUserID LONG,editType VARCHAR(75) null,treatmentDate DATE null,beforeData VARCHAR(75) null,afterData VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table treatment_audit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY treatmentAudit.AuditID ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY treatment_audit.AuditID ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long CRFID_COLUMN_BITMASK = 2L;

	public static final long EDITTYPE_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long LINKID_COLUMN_BITMASK = 16L;

	public static final long PATIENTID_COLUMN_BITMASK = 32L;

	public static final long STATUS_COLUMN_BITMASK = 64L;

	public static final long TEETHNUM_COLUMN_BITMASK = 128L;

	public static final long UUID_COLUMN_BITMASK = 256L;

	public static final long AUDITID_COLUMN_BITMASK = 512L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public TreatmentAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _AuditID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _AuditID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TreatmentAudit.class;
	}

	@Override
	public String getModelClassName() {
		return TreatmentAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TreatmentAudit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TreatmentAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreatmentAudit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TreatmentAudit)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TreatmentAudit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TreatmentAudit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TreatmentAudit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TreatmentAudit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TreatmentAudit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TreatmentAudit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TreatmentAudit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TreatmentAudit, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TreatmentAudit, Object>>();
		Map<String, BiConsumer<TreatmentAudit, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TreatmentAudit, ?>>();

		attributeGetterFunctions.put("uuid", TreatmentAudit::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<TreatmentAudit, String>)TreatmentAudit::setUuid);
		attributeGetterFunctions.put("AuditID", TreatmentAudit::getAuditID);
		attributeSetterBiConsumers.put(
			"AuditID",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setAuditID);
		attributeGetterFunctions.put("crfId", TreatmentAudit::getCrfId);
		attributeSetterBiConsumers.put(
			"crfId",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setCrfId);
		attributeGetterFunctions.put("linkId", TreatmentAudit::getLinkId);
		attributeSetterBiConsumers.put(
			"linkId",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setLinkId);
		attributeGetterFunctions.put("patientID", TreatmentAudit::getPatientID);
		attributeSetterBiConsumers.put(
			"patientID",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setPatientID);
		attributeGetterFunctions.put("teethNum", TreatmentAudit::getTeethNum);
		attributeSetterBiConsumers.put(
			"teethNum",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setTeethNum);
		attributeGetterFunctions.put(
			"editedDate", TreatmentAudit::getEditedDate);
		attributeSetterBiConsumers.put(
			"editedDate",
			(BiConsumer<TreatmentAudit, Date>)TreatmentAudit::setEditedDate);
		attributeGetterFunctions.put(
			"editedUserID", TreatmentAudit::getEditedUserID);
		attributeSetterBiConsumers.put(
			"editedUserID",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setEditedUserID);
		attributeGetterFunctions.put("editType", TreatmentAudit::getEditType);
		attributeSetterBiConsumers.put(
			"editType",
			(BiConsumer<TreatmentAudit, String>)TreatmentAudit::setEditType);
		attributeGetterFunctions.put(
			"treatmentDate", TreatmentAudit::getTreatmentDate);
		attributeSetterBiConsumers.put(
			"treatmentDate",
			(BiConsumer<TreatmentAudit, Date>)TreatmentAudit::setTreatmentDate);
		attributeGetterFunctions.put(
			"beforeData", TreatmentAudit::getBeforeData);
		attributeSetterBiConsumers.put(
			"beforeData",
			(BiConsumer<TreatmentAudit, String>)TreatmentAudit::setBeforeData);
		attributeGetterFunctions.put("afterData", TreatmentAudit::getAfterData);
		attributeSetterBiConsumers.put(
			"afterData",
			(BiConsumer<TreatmentAudit, String>)TreatmentAudit::setAfterData);
		attributeGetterFunctions.put("groupId", TreatmentAudit::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setGroupId);
		attributeGetterFunctions.put("companyId", TreatmentAudit::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setCompanyId);
		attributeGetterFunctions.put("userId", TreatmentAudit::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<TreatmentAudit, Long>)TreatmentAudit::setUserId);
		attributeGetterFunctions.put("userName", TreatmentAudit::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TreatmentAudit, String>)TreatmentAudit::setUserName);
		attributeGetterFunctions.put(
			"createDate", TreatmentAudit::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TreatmentAudit, Date>)TreatmentAudit::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TreatmentAudit::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TreatmentAudit, Date>)TreatmentAudit::setModifiedDate);
		attributeGetterFunctions.put("status", TreatmentAudit::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<TreatmentAudit, Integer>)TreatmentAudit::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", TreatmentAudit::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<TreatmentAudit, Long>)
				TreatmentAudit::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", TreatmentAudit::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<TreatmentAudit, String>)
				TreatmentAudit::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", TreatmentAudit::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<TreatmentAudit, Date>)TreatmentAudit::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getAuditID() {
		return _AuditID;
	}

	@Override
	public void setAuditID(long AuditID) {
		_AuditID = AuditID;
	}

	@Override
	public long getCrfId() {
		return _crfId;
	}

	@Override
	public void setCrfId(long crfId) {
		_columnBitmask |= CRFID_COLUMN_BITMASK;

		if (!_setOriginalCrfId) {
			_setOriginalCrfId = true;

			_originalCrfId = _crfId;
		}

		_crfId = crfId;
	}

	public long getOriginalCrfId() {
		return _originalCrfId;
	}

	@Override
	public long getLinkId() {
		return _linkId;
	}

	@Override
	public void setLinkId(long linkId) {
		_columnBitmask |= LINKID_COLUMN_BITMASK;

		if (!_setOriginalLinkId) {
			_setOriginalLinkId = true;

			_originalLinkId = _linkId;
		}

		_linkId = linkId;
	}

	public long getOriginalLinkId() {
		return _originalLinkId;
	}

	@Override
	public long getPatientID() {
		return _patientID;
	}

	@Override
	public void setPatientID(long patientID) {
		_columnBitmask |= PATIENTID_COLUMN_BITMASK;

		if (!_setOriginalPatientID) {
			_setOriginalPatientID = true;

			_originalPatientID = _patientID;
		}

		_patientID = patientID;
	}

	public long getOriginalPatientID() {
		return _originalPatientID;
	}

	@Override
	public long getTeethNum() {
		return _teethNum;
	}

	@Override
	public void setTeethNum(long teethNum) {
		_columnBitmask |= TEETHNUM_COLUMN_BITMASK;

		if (!_setOriginalTeethNum) {
			_setOriginalTeethNum = true;

			_originalTeethNum = _teethNum;
		}

		_teethNum = teethNum;
	}

	public long getOriginalTeethNum() {
		return _originalTeethNum;
	}

	@Override
	public Date getEditedDate() {
		return _editedDate;
	}

	@Override
	public void setEditedDate(Date editedDate) {
		_editedDate = editedDate;
	}

	@Override
	public long getEditedUserID() {
		return _editedUserID;
	}

	@Override
	public void setEditedUserID(long editedUserID) {
		_editedUserID = editedUserID;
	}

	@Override
	public String getEditType() {
		if (_editType == null) {
			return "";
		}
		else {
			return _editType;
		}
	}

	@Override
	public void setEditType(String editType) {
		_columnBitmask |= EDITTYPE_COLUMN_BITMASK;

		if (_originalEditType == null) {
			_originalEditType = _editType;
		}

		_editType = editType;
	}

	public String getOriginalEditType() {
		return GetterUtil.getString(_originalEditType);
	}

	@Override
	public Date getTreatmentDate() {
		return _treatmentDate;
	}

	@Override
	public void setTreatmentDate(Date treatmentDate) {
		_treatmentDate = treatmentDate;
	}

	@Override
	public String getBeforeData() {
		if (_beforeData == null) {
			return "";
		}
		else {
			return _beforeData;
		}
	}

	@Override
	public void setBeforeData(String beforeData) {
		_beforeData = beforeData;
	}

	@Override
	public String getAfterData() {
		if (_afterData == null) {
			return "";
		}
		else {
			return _afterData;
		}
	}

	@Override
	public void setAfterData(String afterData) {
		_afterData = afterData;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TreatmentAudit.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TreatmentAudit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TreatmentAudit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TreatmentAudit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TreatmentAuditImpl treatmentAuditImpl = new TreatmentAuditImpl();

		treatmentAuditImpl.setUuid(getUuid());
		treatmentAuditImpl.setAuditID(getAuditID());
		treatmentAuditImpl.setCrfId(getCrfId());
		treatmentAuditImpl.setLinkId(getLinkId());
		treatmentAuditImpl.setPatientID(getPatientID());
		treatmentAuditImpl.setTeethNum(getTeethNum());
		treatmentAuditImpl.setEditedDate(getEditedDate());
		treatmentAuditImpl.setEditedUserID(getEditedUserID());
		treatmentAuditImpl.setEditType(getEditType());
		treatmentAuditImpl.setTreatmentDate(getTreatmentDate());
		treatmentAuditImpl.setBeforeData(getBeforeData());
		treatmentAuditImpl.setAfterData(getAfterData());
		treatmentAuditImpl.setGroupId(getGroupId());
		treatmentAuditImpl.setCompanyId(getCompanyId());
		treatmentAuditImpl.setUserId(getUserId());
		treatmentAuditImpl.setUserName(getUserName());
		treatmentAuditImpl.setCreateDate(getCreateDate());
		treatmentAuditImpl.setModifiedDate(getModifiedDate());
		treatmentAuditImpl.setStatus(getStatus());
		treatmentAuditImpl.setStatusByUserId(getStatusByUserId());
		treatmentAuditImpl.setStatusByUserName(getStatusByUserName());
		treatmentAuditImpl.setStatusDate(getStatusDate());

		treatmentAuditImpl.resetOriginalValues();

		return treatmentAuditImpl;
	}

	@Override
	public int compareTo(TreatmentAudit treatmentAudit) {
		long primaryKey = treatmentAudit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TreatmentAudit)) {
			return false;
		}

		TreatmentAudit treatmentAudit = (TreatmentAudit)object;

		long primaryKey = treatmentAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCrfId = _crfId;

		_setOriginalCrfId = false;

		_originalLinkId = _linkId;

		_setOriginalLinkId = false;

		_originalPatientID = _patientID;

		_setOriginalPatientID = false;

		_originalTeethNum = _teethNum;

		_setOriginalTeethNum = false;

		_originalEditType = _editType;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_setModifiedDate = false;
		_originalStatus = _status;

		_setOriginalStatus = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TreatmentAudit> toCacheModel() {
		TreatmentAuditCacheModel treatmentAuditCacheModel =
			new TreatmentAuditCacheModel();

		treatmentAuditCacheModel.uuid = getUuid();

		String uuid = treatmentAuditCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			treatmentAuditCacheModel.uuid = null;
		}

		treatmentAuditCacheModel.AuditID = getAuditID();

		treatmentAuditCacheModel.crfId = getCrfId();

		treatmentAuditCacheModel.linkId = getLinkId();

		treatmentAuditCacheModel.patientID = getPatientID();

		treatmentAuditCacheModel.teethNum = getTeethNum();

		Date editedDate = getEditedDate();

		if (editedDate != null) {
			treatmentAuditCacheModel.editedDate = editedDate.getTime();
		}
		else {
			treatmentAuditCacheModel.editedDate = Long.MIN_VALUE;
		}

		treatmentAuditCacheModel.editedUserID = getEditedUserID();

		treatmentAuditCacheModel.editType = getEditType();

		String editType = treatmentAuditCacheModel.editType;

		if ((editType != null) && (editType.length() == 0)) {
			treatmentAuditCacheModel.editType = null;
		}

		Date treatmentDate = getTreatmentDate();

		if (treatmentDate != null) {
			treatmentAuditCacheModel.treatmentDate = treatmentDate.getTime();
		}
		else {
			treatmentAuditCacheModel.treatmentDate = Long.MIN_VALUE;
		}

		treatmentAuditCacheModel.beforeData = getBeforeData();

		String beforeData = treatmentAuditCacheModel.beforeData;

		if ((beforeData != null) && (beforeData.length() == 0)) {
			treatmentAuditCacheModel.beforeData = null;
		}

		treatmentAuditCacheModel.afterData = getAfterData();

		String afterData = treatmentAuditCacheModel.afterData;

		if ((afterData != null) && (afterData.length() == 0)) {
			treatmentAuditCacheModel.afterData = null;
		}

		treatmentAuditCacheModel.groupId = getGroupId();

		treatmentAuditCacheModel.companyId = getCompanyId();

		treatmentAuditCacheModel.userId = getUserId();

		treatmentAuditCacheModel.userName = getUserName();

		String userName = treatmentAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			treatmentAuditCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			treatmentAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			treatmentAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			treatmentAuditCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			treatmentAuditCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		treatmentAuditCacheModel.status = getStatus();

		treatmentAuditCacheModel.statusByUserId = getStatusByUserId();

		treatmentAuditCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = treatmentAuditCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			treatmentAuditCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			treatmentAuditCacheModel.statusDate = statusDate.getTime();
		}
		else {
			treatmentAuditCacheModel.statusDate = Long.MIN_VALUE;
		}

		return treatmentAuditCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TreatmentAudit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TreatmentAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreatmentAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TreatmentAudit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TreatmentAudit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TreatmentAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreatmentAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TreatmentAudit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TreatmentAudit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TreatmentAudit.class, ModelWrapper.class);

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _AuditID;
	private long _crfId;
	private long _originalCrfId;
	private boolean _setOriginalCrfId;
	private long _linkId;
	private long _originalLinkId;
	private boolean _setOriginalLinkId;
	private long _patientID;
	private long _originalPatientID;
	private boolean _setOriginalPatientID;
	private long _teethNum;
	private long _originalTeethNum;
	private boolean _setOriginalTeethNum;
	private Date _editedDate;
	private long _editedUserID;
	private String _editType;
	private String _originalEditType;
	private Date _treatmentDate;
	private String _beforeData;
	private String _afterData;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private TreatmentAudit _escapedModel;

}